# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xOGeizJjjQ7fg3cYCDt3lbt6Eh6HHX7e
"""

import sys

if len(sys.argv) < 2:
   print("請提供至少一個參數。")
   sys.exit()

    # 印出所有命令列參數
for arg in sys.argv[1:]:
    print(arg)